### PR TITLE
Make it work even in multi-tab context

### PR DESCRIPTION
**Pull request by dbrugne**
Allow Backbone.localStorage to work well in a multi browser tab context (or multi-webView phonegap context).

Simply reload .records() on findAll() call to reset completly collection state.

### CODE REVIEW

**Comment by dbrugne** [comment]
Related: http://stackoverflow.com/questions/17096469/newly-saved-backbone-model-does-not-appear-in-collection-after-fetch

**Comment by jeromegn** [comment]
Can you remove the minified version? I don't want that anymore since it poses risks. I'll do the minification myself :)

**Comment by dbrugne** [comment]
I reverted *backbone.localStorage-min.js* with the last one on your master branch.

FYI if I minified with your own Makefile. :)

**Comment by jeromegn** [comment]
@dbrugne oh yea, not targeted at you specifically. Just what I think is good practice. I can't read a minified file to check if it's really the minified version of the source somebody provided!

**Comment by scott-w** [comment]
@dbrugne I'm going to close this PR as I've updated the code-base for ES6, creating merge conflicts.

I'd really like to discuss improvements in this area so I'd love for you to open a new PR against the updated code.

**Pull request closed without merging**
