### PR TITLE
#168 fail silently when localStorage is disabled or not supported

### PR DESCRIPTION
**Pull request by spenoir**

### CODE REVIEW

**Comment by jeromegn** [comment]
I don't know if that's desirable. Maybe the solution is to catch the exception?

You generally want to know if your mechanism is not working and then notify the user.

**Comment by spenoir** [comment]
But localStorage should be used for throw away temporary data IMO. It shouldn't block your whole application from loading if decide to turn it off. If you are building a javascript web app and localStorage is the only storage you have then you should be warning your users that the app will not work with data disabled

**Comment by spenoir** [comment]
I don't understand why you won't merge this. It only improves it by not breaking your javascript layer when website data is turned off

**Comment by jeromegn** [comment]
One reason I'm not doing it **yet**, is because I don't have that much time to put into this project.

Here's another reason I think is valid: This changes how people use the current implementation. They used to be able to rely on a thrown exception, now it'll just fail silently. It would require a major version bump.

I believe your change is good, but I don't think it warrants a version bump on its own.

For now, why not just override that method in your project? You can simply redefine it like this:

```javascript
var oldBackboneLocalStorage = Backbone.LocalStorage
Backbone.LocalStorage = function(name, serializer){
  if( this.localStorage() )
    return oldBackboneLocalStorage.call(this, name, serializer)
}
```

I can't accommodate every changes. I have been bad at gatekeeping the project before and I try to be better since about a year.

Sorry for not responding earlier, I should have. My mind is elsewhere.

**Comment by spenoir** [comment]
Understood mate, sorry for hassling you. I see why its not a major version, cheers

**Comment by scott-w** [comment]
Hi @spenoir, please see my comment on the related issue. As this has been open for over 2 year, I'm going to close it.

Feel free to re-open an issue and I'll be more than happy to have a discussion.

Best regards,
Scott

**Pull request closed without merging**
